on:
  push:
    branches:
      - main
  pull_request:

name: Tests (nostd)

jobs:
  test-nofeatures:
    name: ${{matrix.rust}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        rust: [1.74.1, stable]
        os: [ubuntu-latest]

    env:
      RUSTFLAGS: ''
      CARGO_PROFILE_DEV_DEBUG: '0' # reduce size of target directory

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Toolchain
        run: rustup default ${{matrix.rust}}

      - name: Check
        run: cargo check --no-default-features --all-targets

      - name: Test
        run: cargo test --release --no-default-features
